defaults:
  job_defaults: &job_defaults
    docker:
      - image: circleci/golang:1.11
  restore_cache_step: &restore_cache_step
    restore_cache:
      keys:
        - go-mod-v1-{{ checksum "go.sum" }}
  save_glide_cache_step: &save_cache_step
    save_cache:
      key: go-mod-v1-{{ checksum "go.sum" }}
      paths:
        - "/go/pkg/mod"

version: 2
jobs:
  test:
    <<: *job_defaults
    steps:
      - checkout
      - *restore_cache_step
      - run: make setup
      - run: make spec
      - *save_cache_step

  deploy:
    <<: *job_defaults
    steps:
      - checkout
      - *restore_cache_step
      - run: make ci-publish-release

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - test
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
